---
name: Build and Deploy url-shortener-frontend-production to CloudFront
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    name: Build and Deploy url-shortener-frontend-production
    runs-on: ubuntu-latest
    env:
      BUCKET: ${{secrets.URL_SHORTENER_FRONTEND_PRODUCTION_BUCKET}}
      DIST: dist
      REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      DIST_ID: ${{secrets.URL_SHORTENER_FRONTEND_PRODUCTION_CLOUDFRONT_DISTRIBUTION_ID}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Install Dependencies
        run: |
          node --version
          npm i

      - name: Build Static Website
        run: npm run build
        # env:
        #   CI: false

      - name: Copy files to the production website with the AWS CLI
        run: |
          aws s3 sync --delete ${{ env.DIST }} s3://${{ env.BUCKET }}

      - name: Copy files to the production website with the AWS CLI
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.DIST_ID }} \
            --paths "/*"
